DELETE FROM public.inventory_movements;
DELETE FROM public.products;
DELETE FROM public.categories;

INSERT INTO public.categories (slug, name, description, image_url, sort_order, is_active, seo_title, seo_description) VALUES
('lounge-sets','Lounge Sets','Complete all-weather lounge groupings for terraces and gardens.','/images/products/riviera-lounge-set.jpg',1,true,'Outdoor Lounge Sets | Silvex','All-weather outdoor lounge sets in teak, powder-coated aluminium and woven rope.'),
('outdoor-sofas','Outdoor Sofas','Modular and fixed outdoor sofas built for sun, rain and salt air.','/images/products/riviera-outdoor-sofa.jpg',2,true,'Outdoor Sofas | Silvex','Weatherproof outdoor sofas with quick-dry foam and solution-dyed fabrics.'),
('outdoor-dining','Outdoor Dining','Teak and stone dining tables made for long evenings outside.','/images/products/lido-teak-dining-set.jpg',3,true,'Outdoor Dining Tables | Silvex','Outdoor dining tables and sets in FSC teak, ceramic and aluminium.'),
('outdoor-chairs','Outdoor Chairs','Dining chairs, armchairs and bar stools for every terrace.','/images/products/kestrel-chair.jpg',4,true,'Outdoor Chairs & Stools | Silvex','Stackable outdoor dining chairs, rope armchairs and bar stools.'),
('sun-loungers','Sun Loungers & Daybeds','Loungers and canopied daybeds for poolside and garden.','/images/products/solano-sun-lounger.jpg',5,true,'Sun Loungers & Daybeds | Silvex','Teak sun loungers and outdoor daybeds with quick-dry cushions.'),
('parasols-shade','Parasols & Shade','Cantilever parasols and market umbrellas in UV-stable canopies.','/images/products/ombra-parasol.jpg',6,true,'Parasols & Outdoor Shade | Silvex','Cantilever parasols and market umbrellas with fade-resistant canopies.'),
('fire-pits','Fire Pits & Heating','Fire pits and patio heaters that extend the season.','/images/products/ember-fire-pit.jpg',7,true,'Fire Pits & Patio Heaters | Silvex','Concrete fire pits and patio heaters for year-round outdoor living.'),
('planters-decor','Planters & Outdoor Decor','Planters, outdoor rugs and finishing pieces.','/images/products/onda-planter.jpg',8,true,'Planters & Outdoor Decor | Silvex','Stone planters, outdoor rugs and accessories for terraces and gardens.');

INSERT INTO public.products (slug, sku, name, description, short_description, price, compare_at_price, category_id, collection, material, color, dimensions, weight_kg, stock_quantity, low_stock_threshold, status, is_featured, is_bestseller, is_new_arrival, rating, reviews_count, images)
SELECT p.slug, p.sku, p.name, p.description, p.short_description, p.price, p.compare_at_price, c.id, p.collection, p.material, p.color, p.dimensions, p.weight_kg, p.stock_quantity, 5, 'active', p.is_featured, p.is_bestseller, p.is_new_arrival, p.rating, p.reviews_count, ARRAY[p.image]
FROM (VALUES
('riviera-lounge-set','SLVX-LNG-001','Riviera 4-Piece Lounge Set','A complete terrace grouping: two-seat sofa, two armchairs and a low teak table. Powder-coated aluminium frames, hand-woven rope backs and quick-dry cushions in solution-dyed acrylic that shrugs off sun and rain.','Sofa, two armchairs and teak table in all-weather rope.',4890,5490,'Riviera','Powder-coated aluminium, olefin rope, FSC teak','Chalk',' Sofa 190 x 84 x 70 cm',96.0,8,true,true,false,4.8,42,'/images/products/riviera-lounge-set.jpg'),
('palma-corner-lounge-set','SLVX-LNG-002','Palma Corner Lounge Set','A deep corner configuration for larger terraces, with a matching ottoman and ceramic-topped coffee table. Marine-grade fixings throughout and covers that unzip for washing.','Deep corner set with ottoman and ceramic table.',5760,NULL,'Palma','Powder-coated aluminium, olefin rope, ceramic','Graphite','Corner 268 x 208 x 68 cm',134.0,4,true,false,true,4.7,18,'/images/products/palma-corner-lounge.jpg'),
('riviera-outdoor-sofa','SLVX-SOF-001','Riviera Three-Seat Outdoor Sofa','Generous three-seat proportions with a hand-woven rope back and reticulated quick-dry foam that drains in minutes after a downpour.','Three-seat outdoor sofa with quick-dry cushions.',2980,3380,'Riviera','Powder-coated aluminium, olefin rope','Chalk','226 x 88 x 70 cm',52.0,10,true,true,false,4.9,64,'/images/products/riviera-outdoor-sofa.jpg'),
('costa-modular-outdoor-sofa','SLVX-SOF-002','Costa Modular Outdoor Sofa','Four modules that reconfigure as your terrace changes. Slatted teak bases lift cushions clear of standing water.','Reconfigurable four-module outdoor sofa in teak.',3420,NULL,'Costa','FSC teak, solution-dyed acrylic','Sand','300 x 92 x 66 cm',88.0,6,true,false,true,4.6,21,'/images/products/costa-modular-sofa.jpg'),
('marbella-outdoor-loveseat','SLVX-SOF-003','Marbella Two-Seat Loveseat','A compact loveseat for balconies, with a woven back that stays cool in direct sun.','Compact two-seat outdoor loveseat.',1980,2240,'Marbella','Powder-coated aluminium, olefin rope','Storm','152 x 82 x 70 cm',34.0,3,false,true,false,4.5,37,'/images/products/marbella-loveseat.jpg'),
('lido-teak-dining-set','SLVX-DIN-001','Lido Teak Dining Set for Six','A solid FSC teak table with six stackable dining chairs. Left unfinished, the teak silvers gracefully; oil it if you prefer the honey tone.','Six-seat teak outdoor dining table and chairs.',3650,4100,'Lido','FSC teak','Natural teak','Table 220 x 100 x 75 cm',118.0,7,true,true,false,4.8,53,'/images/products/lido-teak-dining-set.jpg'),
('ravello-round-outdoor-table','SLVX-DIN-002','Ravello Round Outdoor Dining Table','A four-seat round table with a frost-proof ceramic top that wipes clean and never stains.','Four-seat round table with ceramic top.',1890,NULL,'Ravello','Ceramic, powder-coated aluminium','Travertine','Ø 120 x 75 cm',46.0,9,false,false,false,4.6,24,'/images/products/ravello-outdoor-table.jpg'),
('otto-extending-outdoor-table','SLVX-DIN-003','Otto Extending Outdoor Table','Seats six, extends to ten in one movement. Teak slats with a concealed aluminium leaf mechanism rated for outdoor use.','Extending teak table, seats six to ten.',2240,2560,'Otto','FSC teak, aluminium','Natural teak','200-260 x 100 x 75 cm',72.0,5,true,false,false,4.7,29,'/images/products/otto-extending-table.jpg'),
('kestrel-woven-dining-chair','SLVX-CHR-001','Kestrel Woven Dining Chair','A stackable dining chair with a woven seat and back. Stack six without marking the frames.','Stackable woven outdoor dining chair.',340,NULL,'Kestrel','Powder-coated aluminium, olefin rope','Chalk','56 x 60 x 82 cm',5.4,48,false,true,false,4.7,86,'/images/products/kestrel-chair.jpg'),
('aster-rope-armchair','SLVX-CHR-002','Aster Rope Armchair','A wide lounge armchair woven entirely by hand over a slim aluminium frame, with a quick-dry seat pad.','Hand-woven outdoor lounge armchair.',520,590,'Aster','Powder-coated aluminium, olefin rope','Ecru','76 x 78 x 74 cm',9.2,22,true,false,true,4.8,31,'/images/products/aster-rope-armchair.jpg'),
('bram-outdoor-bar-stool','SLVX-CHR-003','Bram Outdoor Bar Stool','Counter-height stool with a teak footrest and drainage-slotted seat for poolside bars.','Teak and aluminium outdoor bar stool.',290,NULL,'Bram','FSC teak, powder-coated aluminium','Natural teak','42 x 46 x 102 cm',6.1,4,false,false,false,4.4,17,'/images/products/bram-outdoor-stool.jpg'),
('solano-teak-sun-lounger','SLVX-LNGR-001','Solano Teak Sun Lounger','Five-position back, hidden wheels and a slatted teak deck that dries fast. Cushion sold with the lounger.','Reclining teak sun lounger with cushion.',890,1040,'Solano','FSC teak, solution-dyed acrylic','Natural teak','200 x 72 x 38 cm',28.0,14,true,true,false,4.9,58,'/images/products/solano-sun-lounger.jpg'),
('isola-canopy-daybed','SLVX-LNGR-002','Isola Daybed with Canopy','A two-person daybed with an adjustable canopy in UV-stable canvas, for the hottest part of the afternoon.','Two-person outdoor daybed with canopy.',3280,NULL,'Isola','Powder-coated aluminium, canvas, olefin rope','Sand','206 x 158 x 190 cm',92.0,3,true,false,true,4.7,12,'/images/products/isola-daybed.jpg'),
('ombra-cantilever-parasol','SLVX-PAR-001','Ombra Cantilever Parasol','A 3.5 m cantilever parasol that rotates 360° and tilts, with a fade-resistant canopy. Base sold separately.','3.5 m rotating cantilever parasol.',1180,1340,'Ombra','Aluminium, solution-dyed acrylic','Chalk','350 x 350 x 265 cm',38.0,6,false,true,false,4.6,26,'/images/products/ombra-parasol.jpg'),
('vela-market-umbrella','SLVX-PAR-002','Vela Market Umbrella','A classic centre-pole market umbrella in 2.7 m, with a vented crown that steadies it in a breeze.','2.7 m vented market umbrella.',640,NULL,'Vela','FSC eucalyptus, solution-dyed acrylic','Olive','Ø 270 x 250 cm',14.0,18,false,false,false,4.5,33,'/images/products/vela-umbrella.jpg'),
('ember-concrete-fire-pit','SLVX-FIR-001','Ember Concrete Fire Pit','A cast fibre-concrete bowl for wood or a gas insert, with a spark screen and weather cover included.','Cast concrete fire pit with cover.',1240,NULL,'Ember','Fibre-concrete, stainless steel','Ash grey','Ø 90 x 42 cm',64.0,5,true,false,true,4.8,19,'/images/products/ember-fire-pit.jpg'),
('torch-patio-heater','SLVX-FIR-002','Torch Patio Heater','A slim free-standing heater in brushed stainless with a tip-safety cut-out and 9 kW output.','Free-standing 9 kW patio heater.',780,890,'Torch','Brushed stainless steel','Silver','Ø 46 x 224 cm',22.0,8,false,false,false,4.3,14,'/images/products/torch-patio-heater.jpg'),
('onda-stone-planter','SLVX-DEC-001','Onda Stone Planter','A frost-proof cast stone planter with a drainage plug and rippled surface that reads differently through the day.','Frost-proof cast stone planter.',240,NULL,'Onda','Cast stone','Limestone','Ø 48 x 52 cm',26.0,26,false,true,false,4.6,41,'/images/products/onda-planter.jpg'),
('terra-outdoor-rug','SLVX-DEC-002','Terra Outdoor Rug','A flat-woven polypropylene rug that can be hosed down and left to dry in the sun.','Washable flat-woven outdoor rug.',320,380,'Terra','Recycled polypropylene','Terracotta','300 x 200 cm',11.0,12,false,false,true,4.5,22,'/images/products/terra-outdoor-rug.jpg')
) AS p(slug, sku, name, description, short_description, price, compare_at_price, collection, material, color, dimensions, weight_kg, stock_quantity, is_featured, is_bestseller, is_new_arrival, rating, reviews_count, image)
JOIN public.categories c ON c.slug = CASE
  WHEN p.sku LIKE 'SLVX-LNG-%' THEN 'lounge-sets'
  WHEN p.sku LIKE 'SLVX-SOF-%' THEN 'outdoor-sofas'
  WHEN p.sku LIKE 'SLVX-DIN-%' THEN 'outdoor-dining'
  WHEN p.sku LIKE 'SLVX-CHR-%' THEN 'outdoor-chairs'
  WHEN p.sku LIKE 'SLVX-LNGR-%' THEN 'sun-loungers'
  WHEN p.sku LIKE 'SLVX-PAR-%' THEN 'parasols-shade'
  WHEN p.sku LIKE 'SLVX-FIR-%' THEN 'fire-pits'
  ELSE 'planters-decor'
END;